version: '3.7'

services:

 matching-engine:
  build: matching-engine
  external_links:
  - consul
  ports:
  - "8980"
  - "8981"
  - "8982"
  - "8983"
  - "8984"
  - "8082:80"
  - "9997:9997"
  networks:
  - back
  - mutualized

 trade-execution:
   build: trade-execution
   external_links:
   - consul
   ports:
   - "8980"
   - "8982"
   - "8983"
   - "8984"
   - "8081:80"
   - "8080:8080"
   - "9998:9998"
   networks:
   - back
   - mutualized

 pricing:
   build: pricing
   external_links:
   - consul
   ports:
   - "8981"
   - "8084:80"
   - "8085:8085"
   - "9999:9999"
   networks:
   - back
   - mutualized

 market:
   build: market
   external_links:
    - consul
   ports:
   - "9996:9996"
   networks:
   - back
   - mutualized

 docs:
     build: docs
     ports:
     - "8090:80"
     networks:
     - back
     - mutualized

networks:
 back:
  driver: bridge
  external: true
 mutualized:
  external: true